bug fix of rm and rsync command

diff --git a/bin/myrsync b/bin/myrsync
--- a/bin/myrsync
+++ b/bin/myrsync
@@ -8,23 +8,31 @@
 # Usage:
 #   HOST machine is in local network:
 #
-#     Download: $0 [OPTION]... HOST SRC DEST
-#            or $0 [-d|--download] [OPTION]... HOST SRC DEST
+#     Download: $0_end [-d|--download] [OPTION]... HOST SRC DEST
 #     Upload:   $0 [-u|--upload] [OPTION]... HOST SRC [SRC]... DEST
 #
 #
-#   HOST machine is NOT in local network:
+#   HOST machine is _redNOT_end in local network:
 #
-#     Download: $0 [-p|--port-forward] [OPTION]... HOST SRC DEST
-#            or $0 [-d|--download] [-p|--port-forward] [OPTION]... HOST SRC DEST
+#     Download: $0 [-d|--download] [-p|--port-forward] [OPTION]... HOST SRC DEST
 #     Upload:   $0 [-u|--upload] [-p|--port-forward] [OPTION]... HOST SRC [SRC]... DEST
 #
-# Example:
-#   case1: Upload $HOME/foo to $HOME/tmp/ on kingkong (defined in $HOME/.ssh/config)
+#   This command is based on system default rsync, that is
+#   _redmultiple SRC cannot be specified for download_end.
+#
+#
+# Examples:
+#   case1: Upload ~/foo to ~/tmp/ on kingkong (defined in ~/.ssh/config on local machine)
 #     $0 -u kingkong ~/foo ~/tmp/
 #
 #   case2: case1 over global network with port forwarding through MDL's gateway
-#     $0 -u -p kingkong ~/foo ~/tmp/
+#     $0 -u --port-forward kingkong ~/foo ~/tmp/
+#  or $0 -u kingkong ~/foo ~/tmp/ -p
+#  or $0 -p kingkong -u ~/foo ~/tmp/
+#  or $0 -pu kingkong ~/foo ~/tmp/
+#
+# The position of the options is free,
+# but the relative positions of HOST, SRC, and DEST _redmust be preserved_end.
 #
 #
 # Options:
@@ -39,10 +47,28 @@
 
 function help () {
     awk -v CMD="$(basename $0)" 'NR > 2 {
-    if (/^#/) { sub("^# ?", ""); sub("\\$0", CMD); sub("NOT", "\033[1;31mNOT\033[0m"); print }
+    if (/^#/) { sub("^# ?", "");
+                sub("\\$0", "\033[1;36m"CMD"\033[m");
+                sub("_red", "\033[1;31m");
+                sub("_cyan", "\033[1;36m")
+                sub("_end", "\033[m");
+                print }
     else { exit }
     }' $0
-    exit 1
+    exit 0
+}
+
+e_error() {
+    printf " \033[31m%s\033[m\n" "✖ $*" 1>&2
+}
+
+e_red() {
+    printf " \033[31m%s\033[m" "$*"
+    return 0
+}
+
+e_cyan() {
+    printf " \033[36m%s\033[m" "$*"
 }
 
 set -Cu  # removed -e to close ssh tunnel when rsync is failed
@@ -63,19 +89,31 @@ while (( $# > 0 )); do
             IsPortForward=$1
             ;;
         -d | --download)
-            IsDownload=$1
+            if [[ -z ${DIRECTION:-} ]]; then
+                DIRECTION="down"
+            else
+                e_error "Both download and upload are specified."
+                echo "Choose on of them."
+                exit 1
+            fi
             ;;
         -u | --upload)
-            IsUpload=$1
+            if [[ -z ${DIRECTION:-} ]]; then
+                DIRECTION="up"
+            else
+                e_error "Both download and upload are specified."
+                echo "Choose on of them."
+                exit 1
+            fi
             ;;
         -e | --exclude | --exclude=*)
             if [[ -n ${exclude:-} ]]; then
-                echo "Too many --exclude option." 1>&2
+                e_error "Too many --exclude option."
                 exit 1
             elif [[ "$1" =~ ^--exclude= ]]; then
                 exclude=$1
             elif [[ -z "$2" ]] || [[ "$2" =~ ^-+ ]]; then
-                echo "'-e/--exclude' require an argument." 1>&2
+                e_error "'-e/--exclude' require an argument."
                 exit 1
             else
                 exclude="--exclude=$2"
@@ -84,12 +122,12 @@ while (( $# > 0 )); do
             ;;
         -i | --include | --include=*)
             if [[ -n ${include:-} ]]; then
-                echo "Too many --include option." 1>&2
+                e_error "Too many --include option."
                 exit 1
             elif [[ "$1" =~ ^--include= ]]; then
                 include="$1"
             elif [[ -z "${2:-}" ]] || [[ "$2" =~ ^-+ ]]; then
-                echo "'-i/--include' require an argument." 1>&2
+                e_error "'-i/--include' require an argument."
                 exit 1
             else
                 include="--include=$2"
@@ -97,8 +135,13 @@ while (( $# > 0 )); do
             fi
             ;;
         -*)
-            echo "Illegal option -- '$(echo $1 | sed 's/^-*//')'." 1>&2
-            help
+            if [[ "${#1}" = 2 ]]; then
+                e_error "Illegal option -- '$(echo $1 | sed 's/^-*//')'."
+                help
+            else
+                opts=($(echo $1 | sed 's/-//g' | sed 's/./-& /g'))
+                set -- "$@" "${opts[@]}"
+            fi
             ;;
         *)
             if [[ -z ${ARGS:-} ]]; then
@@ -111,10 +154,27 @@ while (( $# > 0 )); do
     shift
 done
 
-[[ -z ${ARGS:-} ]] && help
+[[ -z ${DIRECTION:-} ]] && {
+    e_error "Either download or upload must be specified."
+    exit 1
+}
+
+if [[ -z ${ARGS:-} ]]; then
+    help
+elif [[ ${#ARGS[@]} < 3 ]]; then
+    e_error "Too few arguments -- ${ARGS[@]}"
+    echo "Check usage -- $(e_cyan $(basename $0)) -h"
+    exit 1
+elif [[ ${#ARGS[@]} > 3 && ${IsDownload:-} ]]; then
+    e_error "Too many arguments -- ${ARGS[@]}"
+    echo "This command is based on system default rsync, so it only allows a single SRC of HOST."
+    echo "This means that $(e_red 'multiple directories cannot be specified for download')."
+    exit 1
+fi
+
 
 if [[ -n ${include:-} ]] && [[ -n ${exclude:-} ]]; then
-    echo "Only one of `--include` and `--exclude` can be used." 1>&2
+    e_error "Only one of `--include` and `--exclude` can be used."
     exit 1
 elif [[ -n ${include:-} ]]; then
     exclude="--exclude=*"    
@@ -124,6 +184,7 @@ else
     exclude="--exclude=''"
     include="--include=*"
 fi
+
 
 function hostname_of() {
     ssh -G $1 | awk '/^hostname / { print $2 }'
@@ -135,7 +196,8 @@ function port_of() {
 
 function sshtunnel() {
     if [[ $# -ne 3 ]]; then
-        echo "Usage: sshtunnel HOST HOSTPORT LOCALPORT"
+        e_error "Usage: sshtunnel HOST HOSTPORT LOCALPORT"
+        exit 1
     else
         local host=$(hostname_of $1)
         local port=$2
@@ -166,8 +228,8 @@ function get_nth() {
 
 function mdlrsyncfrom() {
     local host=$1
-    local remotepath=$2
     local remotepath=$(echo $2 | awk -v home="$HOME" '{ sub(home, "\~"); print }')
+    local localpath=$3
     
     sshtunnel $host 22 10022
     rsync $IsDryRun -avz --copy-unsafe-links --progress --bwlimit=5120 --rsh="ssh -p 10022" "${USER}@localhost:${remotepath}" "$localpath" --include='*/' "$include" "$exclude"
@@ -203,23 +265,25 @@ function rsyncto() {
 }
 
 # main
-[[ ${#ARGS} < 3 ]] && {
-    echo "Too few arguments -- ${ARGS}";
-    echo "Check help -- $(basename $0) --help";
-    exit 1;
-}
+case "${DIRECTION}" in
+    up)
+        if [[ ${IsPortForward:-} ]]; then
+            mdlrsyncto ${ARGS[@]}
+        else
+            rsyncto ${ARGS[@]}
+        fi
+        ;;
+    down)
+        if [[ ${IsPortForward:-} ]]; then
+            mdlrsyncfrom ${ARGS[@]}
+        else
+            rsyncfrom ${ARGS[@]}
+        fi
+        ;;
+    *)
+        e_error "Illegal option -- $DIRECTION"
+        ;;
+esac
 
-if [[ -n ${IsPortForward:-} ]]; then
-    if [[ -n ${IsUpload:-} ]]; then
-        mdlrsyncto ${ARGS[@]}
-    else
-        mdlrsyncfrom ${ARGS[@]}
-    fi
-else
-    if [[ -n ${IsUpload:-} ]]; then
-        rsyncto ${ARGS[@]}
-    else
-        rsyncfrom ${ARGS[@]}
-    fi
-fi
+[[ "${IsDryRun:-}" ]] && { e_red "This is dry run. File are unchanged." ; }
 
