Update makefile and installer

diff --git a/etc/install b/etc/install
--- a/etc/install
+++ b/etc/install
@@ -272,6 +272,27 @@ dotfiles_initialize() {
     fi
 }
 
+dotfiles_deploy() {
+    if [ ! -d $DOTPATH ]; then
+        log_fail "$DOTPATH: not found"
+        exit 1
+    fi
+
+    cd "$DOTPATH"
+
+    if is_debug; then
+        :
+    else
+        make deploy
+    fi &&
+
+        e_newline && e_done "Install"
+}
+
+function install_nix() {
+    make nix
+}
+
 # A script for the file named "install"
 dotfiles_install() {
     # 1. Download the repository
@@ -286,7 +307,10 @@ dotfiles_install() {
 
     # 3. Execute all sh files within etc/init/
     # ==> initializing
-    dotfiles_initialize "$@"
+    dotfiles_initialize "$@" &&
+
+    # 4. Install nix with home-manager manually
+    install_nix
 }
 
 
